name: .NET

on:
    push:
        branches: [main]
    pull_request:
        branches: [main]

jobs:
    build:
        runs-on: ubuntu-latest

        steps:
            - uses: actions/checkout@v2

            # Setup dotnet on runner
            - name: Setup .NET
              uses: actions/setup-dotnet@v1
              with:
                dotnet-version: 5.0.x
            
            # install libssl1.1
            # https://stackoverflow.com/a/74948900/10262450
            - name: install libssl1.1 
              run: |
                ln -s /usr/lib/libssl.so.47.0.6 /usr/lib/libssl.so.1.0.0
            
            - name: Restore dependencies
              run: dotnet restore

            - name: Build
              run: dotnet build --no-restore

            - name: Test
              run: dotnet test --no-build --verbosity normal